In [1]:
import numpy as np
import pandas as pd

In [25]:
index = pd.date_range("20200101", periods=10)
index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [5]:
s= pd.Series(np.random.randn(5), index=["a",'b','c','d','e'])
s

a    0.450869
b   -0.432658
c   -0.098538
d    0.099883
e   -1.328717
dtype: float64

In [18]:
np.random.random(5)

array([0.62186193, 0.65872817, 0.33157148, 0.6668164 , 0.25493209])

In [19]:
np.random.randn(4)

array([-0.01203416, -0.14206031,  0.57206148,  0.08975946])

In [24]:
df = pd.DataFrame(np.random.random((4,4)), index=["a",'b','c','d'], columns=["AA",'BB','CC','DD'])
df

AA        BB        CC        DD
a  0.045002  0.215323  0.128108  0.663242
b  0.989019  0.256073  0.650291  0.946116
c  0.713397  0.116419  0.352291  0.461816
d  0.914696  0.120334  0.127658  0.328658

In [29]:
s.head(3)

a    0.450869
b   -0.432658
c   -0.098538
dtype: float64

In [28]:
s.tail(3)

c   -0.098538
d    0.099883
e   -1.328717
dtype: float64

In [30]:
df.head(3)

AA        BB        CC        DD
a  0.045002  0.215323  0.128108  0.663242
b  0.989019  0.256073  0.650291  0.946116
c  0.713397  0.116419  0.352291  0.461816

In [31]:
df.describe()

AA        BB        CC        DD
count  4.000000  4.000000  4.000000  4.000000
mean   0.665529  0.177037  0.314587  0.599958
std    0.429758  0.069767  0.247545  0.268649
min    0.045002  0.116419  0.127658  0.328658
25%    0.546299  0.119355  0.127995  0.428526
50%    0.814047  0.167828  0.240199  0.562529
75%    0.933277  0.225511  0.426791  0.733961
max    0.989019  0.256073  0.650291  0.946116

In [32]:
df[:2]

AA        BB        CC        DD
a  0.045002  0.215323  0.128108  0.663242
b  0.989019  0.256073  0.650291  0.946116

In [35]:
df1 = df.copy()

In [37]:
df1.columns = [i.lower() for i in df1.columns]
df1

aa        bb        cc        dd
a  0.045002  0.215323  0.128108  0.663242
b  0.989019  0.256073  0.650291  0.946116
c  0.713397  0.116419  0.352291  0.461816
d  0.914696  0.120334  0.127658  0.328658

In [43]:
s.array

<PandasArray>
[  0.4508687145499579, -0.43265806254681943, -0.09853792434106215,
  0.09988288371764673,  -1.3287171503454502]
Length: 5, dtype: float64

In [44]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [45]:
s.to_numpy()

array([ 0.45086871, -0.43265806, -0.09853792,  0.09988288, -1.32871715])

In [46]:
np.asarray(s)

array([ 0.45086871, -0.43265806, -0.09853792,  0.09988288, -1.32871715])

to_numpy() gives some control over the dtype of the resulting numpy.ndarray. For example, consider datetimes with timezones. NumPy doesn’t have a dtype to represent timezone-aware datetimes, so there are two possibly useful representations:

An object-dtype numpy.ndarray with Timestamp objects, each with the correct tz
A datetime64[ns] -dtype numpy.ndarray, where the values have been converted to UTC and the timezone discarded
Timezones may be preserved with dtype=object

In [50]:
ser = pd.Series(pd.date_range("2010", periods= 4, tz="CET"))
ser

0   2010-01-01 00:00:00+01:00
1   2010-01-02 00:00:00+01:00
2   2010-01-03 00:00:00+01:00
3   2010-01-04 00:00:00+01:00
dtype: datetime64[ns, CET]

In [54]:
ser.to_numpy(dtype=object)

array([Timestamp('2010-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2010-01-02 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2010-01-03 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2010-01-04 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [55]:
ser.to_numpy(dtype='datetime64[ns]')

array(['2009-12-31T23:00:00.000000000', '2010-01-01T23:00:00.000000000',
       '2010-01-02T23:00:00.000000000', '2010-01-03T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [57]:
pd.set_option('compute.use_bottleneck', False)
pd.set_option('compute.use_numexpr', False)

In [59]:
df = pd.DataFrame({
       'one': pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
       'two': pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
       'three': pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
df

one       two     three
a -1.030532  1.057605       NaN
b  0.559754 -0.076542  0.681018
c -2.059739  0.164268  0.232494
d       NaN -0.022795 -0.248235

In [60]:
df.iloc[1]

one      0.559754
two     -0.076542
three    0.681018
Name: b, dtype: float64

In [61]:
df['two']

a    1.057605
b   -0.076542
c    0.164268
d   -0.022795
Name: two, dtype: float64