In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.random(10)

array([0.42888887, 0.36280888, 0.51081565, 0.2251271 , 0.49620628,
       0.62747578, 0.88185148, 0.91977778, 0.67975926, 0.78440634])

In [3]:
np.random.random((10,5))

array([[0.17534537, 0.96752237, 0.25556557, 0.50204003, 0.94266278],
       [0.13815161, 0.57214353, 0.34749934, 0.74813755, 0.06782801],
       [0.86234474, 0.72724788, 0.04620927, 0.40431461, 0.58367747],
       [0.5157217 , 0.61504088, 0.68753489, 0.49826384, 0.21386182],
       [0.35953352, 0.73618205, 0.46899433, 0.38952136, 0.93114444],
       [0.96974846, 0.20297101, 0.53460063, 0.40884808, 0.88995046],
       [0.57037056, 0.58258532, 0.68952696, 0.7474188 , 0.36310639],
       [0.30219856, 0.09056737, 0.53563873, 0.38050544, 0.48797239],
       [0.04885601, 0.78103068, 0.22130828, 0.17053571, 0.20083919],
       [0.65530387, 0.27067372, 0.20885857, 0.8711259 , 0.54102573]])

In [4]:
np.random.rand(10,5)

array([[0.6392341 , 0.80587331, 0.68926026, 0.34991575, 0.97974773],
       [0.18102029, 0.48927706, 0.22189382, 0.12511527, 0.07412391],
       [0.28647055, 0.05477574, 0.59085467, 0.06964673, 0.67719394],
       [0.22656508, 0.03775774, 0.30109704, 0.02561533, 0.80904211],
       [0.619643  , 0.96417386, 0.63406001, 0.66562578, 0.31196685],
       [0.84594435, 0.39687642, 0.329856  , 0.37701438, 0.98970707],
       [0.23703313, 0.61889367, 0.16442422, 0.5813601 , 0.40036352],
       [0.64307277, 0.68153012, 0.59413463, 0.53897306, 0.54161613],
       [0.45440722, 0.29249066, 0.04999099, 0.66653659, 0.92175431],
       [0.63318234, 0.16728223, 0.61259124, 0.73276695, 0.36302312]])

In [5]:
np.random.randn(10,5)

array([[-0.83434683, -0.83691187,  1.04109819, -0.98483543, -0.70248977],
       [ 0.71934976, -0.10213796, -0.17795656, -0.62703215, -0.01624405],
       [-0.83014059, -0.42813531, -0.21135135,  3.303304  ,  1.10035018],
       [-0.35938866,  0.31468698,  0.44773863, -1.08755965,  0.39556737],
       [-1.0499959 , -0.43268678, -0.23318501,  0.5586935 ,  0.52674153],
       [ 0.54126614,  1.59980524,  0.544393  ,  0.38541516, -0.13808203],
       [ 0.19919842, -1.6004929 , -0.92235899,  0.41219043, -1.21395122],
       [-0.31654501, -0.05362197, -0.04965456, -0.81882284, -1.57605134],
       [ 0.98609361, -1.27464862,  0.43038722, -0.04931669, -0.87942925],
       [ 0.78620274,  0.06947663, -0.14114946, -0.29520904, -1.05194092]])

In [6]:
np.random.randn(10)

array([ 0.47492163, -0.22895746,  0.84553308,  1.07252011,  0.98937995,
       -1.69104149, -0.07881665, -0.15894286,  1.66855772, -0.77374812])

In [7]:
np.random.rand(14)

array([0.0581014 , 0.6167771 , 0.29685758, 0.47654144, 0.49294453,
       0.48330285, 0.66266687, 0.73806222, 0.98448605, 0.84068958,
       0.30929078, 0.07310984, 0.27605729, 0.56466438])

In [8]:
np.random.randint(48)

28

In [9]:
np.random.randint((10,6))

array([8, 3])

In [10]:
np.random.normal(20)

17.27985994503867

In [11]:
np.random.normal((10,4))

array([8.0432111 , 3.59037296])

In [12]:
np.random.normal(10,4)

17.865787245748095

In [20]:
a = np.random.RandomState.rand(3)
a

TypeError: descriptor 'rand' requires a 'numpy.random.mtrand.RandomState' object but received a 'int'